/// Flutter icons Notes
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Notes
///      fonts:
///       - asset: fonts/Notes.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NotesIcons {
  NotesIcons._();

  static const _kFontFam = 'Notes';

  static const IconData whole = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData quarter = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData eight = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData half = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData sixteen = IconData(0xe804, fontFamily: _kFontFam);
}
