/// Flutter icons Notes
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Notes
///      fonts:
///       - asset: fonts/Notes.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Notes {
  Notes._();

  static const _kFontFam = 'Notes';

  static const IconData eight_pause = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData eight_reversed =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData eight = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData half_pause = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData half_reversed = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData half = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData quarter_pause = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData quarter_reversed =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData quarter = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData sixteen_pause = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData sixteen_reversed =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData sixteen = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData whole_pause = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData whole = IconData(0xe80d, fontFamily: _kFontFam);
}
